<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>x86;AnyCPU</Platforms>
    <RootNamespace>CrazyKTV_SongMgr</RootNamespace>
    <AssemblyName>CrazyKTV_SongMgr</AssemblyName>
    <ApplicationIcon>Resources\SongMgr.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <CodecDir>Codec_x86</CodecDir>
    <NoWarn>$(NoWarn);SYSLIB0011;CA1416;MSB3270;CS0168</NoWarn>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.60" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Stub.System.Data.SQLite.Core.NetStandard" Version="1.0.118" />
    <PackageReference Include="System.Data.OleDb" Version="8.0.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CrazyKTV_MediaKit">
      <HintPath>Codec_x86\CrazyKTV_MediaKit.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="SongMgr\CrazySongMgr.mdb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SongMgr\Custom.lang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SongMgr\CrazySongEmpty.mdb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SongMgr\Update\UpdateDB.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Tools\ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Tools\ffplay.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Tools\ffprobe.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(PublishProtocol)' == ''">
    <!-- Copy Codec files during build -->
    <Exec Command="xcopy &quot;$(ProjectDir)$(CodecDir)&quot; &quot;$(TargetDir)$(CodecDir)\&quot; /E /I /Y" />
  </Target>

</Project>